"""rename address

Revision ID: ac203df3bf04
Revises: c9555ae321e9
Create Date: 2025-09-10 03:06:21.669686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac203df3bf04'
down_revision = 'c9555ae321e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    
    # ### end Alembic commands ###
